function genListAndLibFiles(root_folder, vector_columns_size, session_type)
%GENLIBFILES Generates HTK helper files that live in the lib folder

dict_content = sprintf([...
    'adam adam\n'...
    'agne agne\n'...
    'bradley bradley\n'...
    'cameron cameron\n'...
    'darcey darcey\n'...
    'dylan dylan\n'...
    'georgiana georgiana\n'...
    'jack jack\n'...
    'james james\n'...
    'jordan jordan\n'...
    'jonathan jonathan\n'...
    'liam liam\n'...
    'max max\n'...
    'mikhayla mikhayla\n'...
    'rob rob\n'...
    'shaun shaun\n'...
    'sophie sophie\n'...
    'tan tan\n'...
    'tom tom\n'...
    'teodora teodora\n'...
    'sil sil\n'
    ]);

words_content = sprintf([...
    'adam\n'...
    'agne\n'...
    'bradley\n'...
    'cameron\n'...
    'darcey\n'...
    'dylan\n'...
    'georgiana\n'...
    'jack\n'...
    'james\n'...
    'jordan\n'...
    'jonathan\n'...
    'liam\n'...
    'max\n'...
    'mikhayla\n'...
    'rob\n'...
    'shaun\n'...
    'sophie\n'...
    'tan\n'...
    'tom\n'...
    'teodora\n'...
    'sil\n'
    ]);

gram_content = sprintf([...
    '$name = adam | agne | bradley | cameron | darcey\n'...
    '| dylan | georgiana | jack | james | jordan\n'...
    '| jonathan | liam | max | mikhayla | rob\n'...
    '| shaun | sophie | tan | tom | teodora;\n'...
    '\n'...
    '([sil] < $name > [sil])\n'...
    ]);

% 4 STATE PROTOTYPE FILES WRITING STAGE
writeProtoFile(strcat(root_folder, "lib/proto4State.txt"), 4, vector_columns_size);


% 8 STATE PROTOTYPE FILES WRITING STAGE
writeProtoFile(strcat(root_folder, "lib/proto8State.txt"), 8, vector_columns_size);

% 16 STATE PROTOTYPE FILES WRITING STAGE
writeProtoFile(strcat(root_folder, "lib/proto16State.txt"), 16, vector_columns_size);

% WORDS FILE WRITING STAGE
writeTxtFile(strcat(root_folder, "lib/words"), words_content);

% DICTIONARY FILE WRITING STAGE
writeTxtFile(strcat(root_folder, "lib/dict"), dict_content);

% GRAMMAR FILE WRITING STAGE
writeTxtFile(strcat(root_folder, "lib/GRAM"), gram_content);

% LISTS FILES WRITING STAGE
writeListFile(root_folder, session_type);
end